[toolchain]
anchor_version = "0.32.1"

[features]
resolution = false
seeds = false
skip-lint = false

[programs.localnet]
token_distributor = "2Ab8No85xrnnd2rFamKjQqGAK6Qu9EQ4eEh59oaZEPBL"

[programs.devnet]
solana_token_pump = "2Ab8No85xrnnd2rFamKjQqGAK6Qu9EQ4eEh59oaZEPBL"


[provider]
cluster = "Localnet"
#cluster = "devnet"
#cluster = "https://api.mainnet-beta.solana.com"
wallet = "/Users/user/.config/solana/id.json"


[scripts]
#test = "RUST_LOG=error yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/token_distributor_bankrun.ts"
#test = "RUST_LOG=info yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/token_distributor_litesvm.ts"
#test = "RUST_LOG=error yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/token_distributor_litesvm.ts"
#test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/*.ts"
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/token_distributor_litesvm.ts"
